CREATE TABLE IF NOT EXISTS bot_response (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  response VARCHAR(255) NOT NULL,
);
CREATE TABLE IF NOT EXISTS user_message_words (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  word VARCHAR(255) NOT NULL,
  bot_response_id INTEGER NOT NULL,
  FOREIGN KEY(bot_response_id) REFERENCES bot_responses(id) ON DELETE CASCADE
);
